apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amd-gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: amd-gpu-operator
  project: default
  source:
    path: helm-charts-openshift
    repoURL: https://github.com/jharmison-redhat/amd-gpu-operator
    targetRevision: 215cd60e2c3d9ff93a76a34367fd611fbde4ebce
    helm:
      valuesObject:
        controllerManager:
          manager:
            image:
              tag: v1.4.0
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: amd-gpu-operator-kmm-cluster-ca
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      name: amd-gpu-operator-kmm-service-ca
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
