apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amd-gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: kube-amd-gpu
  project: default
  source:
    path: charts/amd-gpu-operator
    repoURL: git@github.com:jharmison-redhat/framework-okd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
