apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amd-gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: amd-gpu-operator
  project: default
  source:
    path: helm-charts-openshift
    repoURL: https://github.com/ROCm/gpu-operator
    targetRevision: 4863659a11495de990b62e4a1ba92ef27aa038fc
    helm:
      valuesObject:
        controllerManager:
          manager:
            image:
              tag: v1.4.0
        kmm:
          enabled: false
        nfd:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
