apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amd-gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: amd-gpu-operator
  project: default
  sources:
  - path: helm-charts-openshift
    repoURL: https://github.com/ROCm/gpu-operator
    targetRevision: 4863659a11495de990b62e4a1ba92ef27aa038fc
    helm:
      valueFiles:
        - $values/clusters/okd.jharmison.dev/values/amd-gpu-operator/values.yaml
  - repoURL: git@github.com:jharmison-redhat/framework-okd.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
