apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    path: charts/cert-manager
    repoURL: git@github.com:jharmison-redhat/framework-okd.git
    targetRevision: HEAD
#    helm:
#      valueFiles:
#        - ../../clusters/okd.jharmison.dev/values/cert-manager/values.yaml
#        - secrets+age-import:///helm-secrets-private-keys/argo.txt?../../clusters/okd.jharmison.dev/values/cert-manager/secrets.enc.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
