apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  destination:
    name: in-cluster
    namespace: vllm
  project: default
  sources:
  - path: charts/chat
    repoURL: https://github.com/rh-aiservices-bu/vllm-quickstart
    targetRevision: HEAD
    helm:
      valueFiles:
        - $values/clusters/okd.jharmison.dev/values/chat/values.yaml
        - secrets+age-import:///helm-secrets-private-keys/argo.txt?$values/clusters/okd.jharmison.dev/values/chat/secrets.enc.yaml
  - repoURL: git@github.com:jharmison-redhat/framework-okd.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
