apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendatahub
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  destination:
    name: in-cluster
    namespace: opendatahub
  project: default
  source:
    path: charts/opendatahub
    repoURL: git@github.com:jharmison-redhat/framework-okd.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../clusters/okd.jharmison.dev/values/opendatahub/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
        openshift.io/cluster-monitoring: "true"
